port: $(PORT)
sessionSecret: 9A4HoFDjdvGCEsxTI8rByGOwfkw6jkPEatp
title: Normative Employee Handbook
host: http://handbook.normative.com
db: $(MONGODB_URI)
public: true
auth:
  google:
    enabled: true
    clientId: 142259933371-tekhs7qcequuesue6028kl31qfvl9mni.apps.googleusercontent.com
    clientSecret: UvJX1n0SjrSYyDc9rFWHj-yG
git:
  url: https://github.com/normative/wiki-heroku.git
  branch: master
  auth:
    type: basic
    username: andymac
    passwoard: $(GIT_PASS)
    sslVerify: true
  signature:
    name: Andy MacDonald
    email: andy_macd@me.com
